### ISSUE TITLE
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by hyx007** [danielsnider/MapViz-Tile-Map-Google-Maps-Satellite#1]
Hi, I'm really delighted to know that there is a tool to download map files while using mapviz. But when I run the commands:   `docker run -p 8080:8080 -v ~/mapproxy:/mapproxy -d -t danielsnider/mapproxy `      
I got the error: 
**docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.**
I never use docker before, and I have tried to run this comman as root and I have also tried to run：
`eval "$(docker-machine env default)"`
but it still doesn't work, can you help me to fix this problem? Thx a lot

**Comment by danielsnider** [comment]
I think you need to add sudo to the command:

`sudo docker run -p 8080:8080 -v ~/mapproxy:/mapproxy -d -t danielsnider/mapproxy`


Works?

I think I'll update the readme with this.

Thanks!

**Comment by hyx007** [comment]
Yes, it works, thank you very much. But I'm not sure whether the crux of the matter is the lack of root permission or not, because I have tried to run this comman as the root permission before, it doesn't work. And I run：`sudo apt-get install -y docker.io` just before to run `sudo docker run -p 8080:8080 -v ~/mapproxy:/mapproxy -d -t danielsnider/mapproxy` again. Anyway, I'm so happy it works! Really appreciated !!
