### ISSUE TITLE
GPS does not update on the map

### ISSUE THREAD

**Issue by ganhao89** [danielsnider/MapViz-Tile-Map-Google-Maps-Satellite#2]
Great work! I was able to show the google map on my mapviz and it worked even when offline if I cached the images. However, I have problem showing the GPS data (/gps/fix, /gps/filtered, etc....) on the map. It only shows the first location, and then refuses to update when I move my robot. It shows correctly when I use other maps. Do you have an idea what might be the problem?

**Comment by danielsnider** [comment]
When you have this problem try clicking "Save" again where you name your maptile URL. That fixes the map not loading new tiles. Sorry I'm not sure. I only have general suggestions like make sure the GPS layer is actually on top of the map tile layer, try updating to the latest mapviz, use rostopic echo to confirm messages are being sent, check your frame ID in the message and mapviz. Also, check the setting of the number of GPS points to display is greater than one. If you still have trouble try asking on the official mapviz github project.
