### ISSUE TITLE
Load tile Map with Network ERROR

### ISSUE THREAD

**Issue by pjrambo** [danielsnider/MapViz-Tile-Map-Google-Maps-Satellite#5]
Hi, @danielsnider 
Thank you for your tool. I'm using your tool and find an issue. I'm very appreciate if you could give me some advice.
After followed your instructions, I had set up the docker. I could see the map on both http://localhost:8080/wmts/gm_layer/gm_grid/0/0/0.png 
and
http://127.0.0.1:8080/demo/ .
But, when I added the tile map in the mapviz and click the "save" button, the status change to OK but I could not see the map loaded in mapviz. I tried to re-launch the mapviz. There was still nothing but some ERROR in the terminator like below.
[7f2541e72880] [/mapviz_pj_18058_202514917221692565/ImageCache::NetworkError:251]: NETWORK ERROR
[7f2541e72880] [/mapviz_pj_18058_202514917221692565/ImageCache::NetworkError:251]: NETWORK ERROR
[7f2541e72880] [/mapviz_pj_18058_202514917221692565/ImageCache::NetworkError:251]: NETWORK ERROR
[7f2541e72880] [/mapviz_pj_18058_202514917221692565/ImageCache::NetworkError:251]: NETWORK ERROR
Have you ever met this issue before? I'm struggled with it for a long time. That is very nice if you could give me a hand. Thank you very much.
Best, wishes

**Comment by danielsnider** [comment]
I've never seen this one. You're sure there is no issue with your internet
connection? No firewall or antivirus that would prevent the mapviz process
from making network connections? Does mapviz work without errors when there
is no map layer and thus no need for internet? You're ROS is working
without issues? ROS nodes can communicate without issue?

Daniel Snider ツ

**Comment by pjrambo** [comment]
Thank you for your reply. I'm sure that my internet connection is fine. And if there is no map layer, no network error. Also, my ros is working fine, I can draw other topics in mapviz. Do you know how to set mapviz to access the internet?

**Comment by danielsnider** [comment]
I’m not sure what to suggest except to search google with your error and discuss it with the mapviz devs on their Github issues page.

**Comment by pjrambo** [comment]
OK, thanks anyway

**Comment by arm3nyn** [comment]
run mapproxy directory this again: sudo docker run -p 8080:8080 -d -t -v ~/mapproxy:/mapproxy danielsnider/mapproxy
it works for me
